language: scala
sudo: false
jdk:
- oraclejdk8
dist: trusty
env:
  global:
  - TRAVIS_SBT_VERSION="1.2.8"
  - secure: VGYhEth2C74Jwr8XpARzW7gj/Zgxug07FfjJnLMBO8uETbFybqtN4O4r03uVvSWwjovHOm+PTAxBzklsKWVPQv2D0JU/nji96Sh9xUSAIgLdLTedcgSNZ9NIlk8SdmiE7qoC4vMLpVMzl5p6XKsF/yVejuLoL+Ehq/qDsR3nAvQoIZmDgHapCYbdM9jPjyCgPPdDK7GYfO9qvOtbma4wvX0ntZGR7PswFDdpXpQaGLtkbPwc6O+lIjnxfy2+IW/B1fWRpWbRR4F+nK9T0qHxUDa0hMczmSNwq/GdzEH+P0CZSSOr7SNUmRHfFStNIKb6dJHboUFwiCqalAYRhNsc9F8oOb3KKZ5+zuMsPatNGdiWBQLFhPyfA5ofHaTP2bMN4xOyVyN4i7QE12bfYm/UEVPqOrQXD46W2URKdS8JFuNkJ6S0lHW8ld/Bh0/YRlDO0ylZkCdNlUYOjlu6gg28GhzGShSgA58B09O5GMufbPKz7/2b0ZWb26K5Kj0muIsgXc4/nhT41RpAXoIv/v1HXYLWGIC5j21pRbfxocj+k9WaEG2vSFfTzniyGA53L96hZFB+Xglm8vReYxpeYUDr/G7a5iMAIn5oqmMKJQo6jMrAtyks8nLbs5zDRqJ8f0NXDTeWZo42FnRPk7BkqyK0qEQ8zUwIQI67kWKr1BmEHq0=
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+$/
before_install:
- nvm install 12 &&
  nvm use 12
- node --version &&
  npm --version
#- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6 &&
#  export PATH=$HOME/.yarn/bin:$PATH
script:
- sbt coverage test &&
  sbt coverageAggregate coveralls &&
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" -o "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]; then
    if [ -z "$TRAVIS_TAG" ]; then
      echo "Build and pack";
      sbt clean "project farjs-app" fullOptJS::webpack;
      cd app/target/scala-2.13/scalajs-bundler/main;
      npm run build;
      npm pack;
    else
      VERSION="$(echo "${TRAVIS_TAG}" | cut -d'v' -f 2)";
      echo "Publish a release version=$VERSION for tag $TRAVIS_TAG";
      version=$VERSION sbt clean "project farjs-app" fullOptJS::webpack;
      cd app/target/scala-2.13/scalajs-bundler/main;
      npm run build;
      npm pack;
      echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc;
      npm publish farjs-app-${VERSION}.tgz;
    fi
  else
    echo "This is not a master branch commit. Skipping the publish/release step";
  fi
cache:
  directories:
  - ~/.npm
  - ~/.nvm
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
