name: Bun CI

on:
  push:
    paths-ignore:
      - "*.md"
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.2.0"

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            ~/work/farjs/farjs/bun.lockb
          key: ${{ runner.os }}-bun-cache-v5-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-bun-cache-v5-

      - name: Run tests
        run: |
          bun install
          bun run sql-bundle
          bun test
