name: Windows CI

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
#        cache: 'npm'
#        cache-dependency-path: '**/package-lock.json'

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: 'sbt'

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: |
          ~/AppData/Roaming/npm
          D:/a/farjs/farjs/app/target/scala-2.13/scalajs-bundler/main/node_modules
          D:/a/farjs/farjs/app/target/scala-2.13/scalajs-bundler/main/package-lock.json
          D:/a/farjs/farjs/app/target/scala-2.13/scalajs-bundler/test/node_modules
          D:/a/farjs/farjs/app/target/scala-2.13/scalajs-bundler/test/package-lock.json
          D:/a/farjs/farjs/filelist/target/scala-2.13/scalajs-bundler/test/node_modules
          D:/a/farjs/farjs/filelist/target/scala-2.13/scalajs-bundler/test/package-lock.json
          D:/a/farjs/farjs/ui/target/scala-2.13/scalajs-bundler/test/node_modules
          D:/a/farjs/farjs/ui/target/scala-2.13/scalajs-bundler/test/package-lock.json
          D:/a/farjs/farjs/dao/target/scala-2.13/scalajs-bundler/test/node_modules
          D:/a/farjs/farjs/dao/target/scala-2.13/scalajs-bundler/test/package-lock.json
          D:/a/farjs/farjs/fs/target/scala-2.13/scalajs-bundler/test/node_modules
          D:/a/farjs/farjs/fs/target/scala-2.13/scalajs-bundler/test/package-lock.json
        key: ${{ runner.os }}-node_modules-cache-v3-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-cache-v3-

    - name: Run tests
      run: |
        sbt test
